Repository RedHatInsights/trust-frontend, pull requests merged in 2020-09, with the labels that each got.

#8 Restores translation/extraction capabilities
  .babelrc
  build/messages/src/Messages.json
  locales/data.json
  locales/translations.json
  package-lock.json
  package.json
  src/Messages.js
  src/Utilities/mergeMessages.js
Labels: bug

#9 Add FAQ tab content
  package-lock.json
  package.json
  src/App.scss
  src/Components/Tabs/FAQ.js
  src/Messages.js
  src/Routes/TrustTabs/TrustTabs.js
Labels: enhancement

#10 Hookup faq to api, update deps
  package-lock.json
  package.json
  src/Components/Tabs/FAQ.js
  src/Messages.js
Labels: enhancement

#11 Addresses ux feedback, updates deps, changes the world 🤯👽👾
  package-lock.json
  package.json
  src/Components/CardCollection/CardCollection.js
  src/Components/CardCollection/CardCollection.scss
  src/Components/Tabs/DataCollection.js
  src/Components/Tabs/DataProtection.js
  src/Messages.js
  src/Routes/TrustTabs/TrustTabs.js
  src/Routes/TrustTabs/TrustTabs.scss
Labels: enhancement

#12 Make some readme changes 🤠
  README.md
Labels: documentation
